import Head from "next/head";
import Image from "next/image";
import photo from "../components/Images/prova0000.jpg";
import { Projects } from "../components/Projects/projects";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Image src={photo} className={styles.photo} />
      <Projects />
    </div>
  );
}
