import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import photo from "../components/Images/prova0000.jpg";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.photo}>
        <Image src={photo} layout="responsive" />
      </div>

      <div className={styles.Pages}>
        <Link href="myprojects">
          <a className={styles.buttons}>
            <a>My Projects</a>
          </a>
        </Link>
        <Link href="myprojects">
          <a className={styles.buttons}>
            <a>Social</a>
          </a>
        </Link>
      </div>
    </div>
  );
}
